### ISSUE TITLE
Java版のテストのソースコードは外に公開しても大丈夫なのか？

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTM-aist-Java#56]
OpenRTM-aist C++版、Python版の単体テストのソースコードは現在は本体から切り離されており、外には非公開になっています。
ただの確認ですが、Java版の単体テストは本体から切り離していないので公開しても大丈夫という事でしょうか？

**Comment by n-ando** [comment]
現状のまま。
